services:
  - type: web
    name: monderh
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_USERNAME
        value: contact@monderh.fr
      - key: MAIL_PASSWORD
        sync: false
    healthCheckPath: /
    autoDeploy: true 